openapi: 3.1.0
info:
  title: SGSI Project Store
  description: Backend compartido para los GPTs de seguridad. Guarda y recupera información por projectId.
  version: 1.0.2
servers:
  - url: https://sgsi-backend-default-rtdb.firebaseio.com
paths:
  /projects/{projectId}.json:
    get:
      operationId: getProjectData
      summary: Recupera los datos completos de un proyecto SGSI.
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del proyecto recuperados con éxito.
          content:
            application/json:
              schema:
                type: object
                required: [cliente, sector, nivelMadurez]
                properties:
                  cliente:
                    type: string
                  sector:
                    type: string
                  nivelMadurez:
                    type: string
                  normativas:
                    type: array
                    items:
                      type: string
                  iocList:
                    type: array
                    items:
                      type: object
                  hallazgosTecnicos:
                    type: array
                    items:
                      type: string
                  controlesExistentes:
                    type: array
                    items:
                      type: string
                  politicasGeneradas:
                    type: array
                    items:
                      type: string
                  sops:
                    type: array
                    items:
                      type: string
                  rtm:
                    type: array
                    items:
                      type: string
                  recomendacionesHumanas:
                    type: array
                    items:
                      type: string
                  estado:
                    type: string
    put:
      operationId: saveProjectData
      summary: Guarda o actualiza los datos completos de un proyecto SGSI.
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [cliente, sector, nivelMadurez]
              properties:
                cliente:
                  type: string
                sector:
                  type: string
                nivelMadurez:
                  type: string
                normativas:
                  type: array
                  items:
                    type: string
                iocList:
                  type: array
                  items:
                    type: object
                hallazgosTecnicos:
                  type: array
                  items:
                    type: string
                controlesExistentes:
                  type: array
                  items:
                    type: string
                politicasGeneradas:
                  type: array
                  items:
                    type: string
                sops:
                  type: array
                  items:
                    type: string
                rtm:
                  type: array
                  items:
                    type: string
                recomendacionesHumanas:
                  type: array
                  items:
                    type: string
                estado:
                  type: string
      responses:
        '200':
          description: Proyecto actualizado correctamente.
