openapi: 3.1.0
info:
  title: SGSI Project Store
  description: Backend compartido para los GPTs de seguridad. Guarda y recupera información por projectId.
  version: 1.0.0
servers:
  - url: https://sgsi-backend-default-rtdb.firebaseio.com
paths:
  /projects/{projectId}.json:
    get:
      operationId: getProjectData
      summary: Recupera los datos completos de un proyecto SGSI.
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Datos del proyecto recuperados con éxito.
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: saveProjectData
      summary: Guarda o actualiza los datos completos de un proyecto SGSI.
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Proyecto actualizado correctamente.
